[pytest]
# Минимально необходимая версия pytest для запуска тестов
minversion = 8.0

# addopts (additional options) — дефолтные флаги, которые будут применяться при КАЖДОМ запуске pytest
# -v: подробный вывод (verbose)
# --tb=short: укороченный и понятный вывод ошибок (traceback)
# --alluredir=allure-results: автоматический сбор сырых результатов Allure в указанную папку
# --clean-alluredir: автоматическая очистка папки allure-results перед каждым запуском тестов
addopts = -v --tb=short --alluredir=allure-results --clean-alluredir

# testpaths — папки, в которых pytest должен искать тесты по умолчанию
testpaths = 
    tests

# python_files — шаблоны имен файлов, которые pytest считает тестовыми
python_files = test_*.py

# Регистрация кастомных маркеров, чтобы избежать предупреждений (warnings) в консоли
markers =
    smoke: быстрые критические тесты для проверки работоспособности
    regression: полные регрессионные тесты
